language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php:
      - 7.4snapshot
      - nightly

before_script:
  - composer install

script:
  - composer build

notifications:
  email: false
