name: Check code style

on: push

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm clean-install

      - name: Check code style for PHP
        run: composer cs

      - name: Check code style for CSS and JavaScript
        run: npm run cs
